PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE 'Request' (
    'ID' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    'Type' INTEGER NOT NULL, 
    'Number' INTEGER NOT NULL, 
    'Date' DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    'DateClose' DATETIME,
    'Desc' TEXT, 
    'Append' TEXT, 
    'Contact' TEXT, 
    'Name' TEXT, 
    'Addr' TEXT
);

CREATE TABLE 'ReqText' (
    'ID' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    'RequestID' INTEGER NOT NULL,
    'Date' DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    'Text' TEXT NOT NULL
);

DELETE FROM sqlite_sequence;

CREATE INDEX 'IDX_RID_DATE' ON "ReqText" ("RequestID" ASC, "Date" ASC);
CREATE UNIQUE INDEX 'IDX_TYPE_NUMDER' ON "Request" ("Type" ASC, "Number" ASC);

COMMIT;
